api/articles/:article_d
Coding-Plumber/BE-News pull request #4
Opened 2023-02-21 14:33 UTC by Coding-Plumber

2023-02-21 14:43 UTC, JVal-NC commented on __tests__/apiArticles.test.js
> +              new Date(b.created_at) - new Date(a.created_at),
This looks complicated is there a simpler way of doing this?

2023-02-21 15:00 UTC, JVal-NC commented on __tests__/apiArticles.test.js
> +        response.body.articles.forEach((article) => {
This is ok but toMatchObject would be cleaner and easier for you. Have a look at it when you get the chance.

2023-02-21 15:00 UTC, JVal-NC commented on __tests__/apiArticles.test.js
> +      .get("/non-existent")
This test is only needed once, I can see a repeat of the same test elsewhere.

2023-02-21 15:01 UTC, JVal-NC commented on __tests__/apiArticles.test.js
> +          expect(articles).toBeSorted({
Look at jest-sorted for this

2023-02-21 15:02 UTC, JVal-NC commented on __tests__/apiTopics.test.js
> +});
Test on line 16 only checks the properties at index 0 and not the other topics.

2023-02-21 15:03 UTC, JVal-NC commented on __tests__/articles-article_id.test.js
> +        expect(response.body.article).toEqual({"article_id": 3, "article_img_url": "https://images.pexels.com/photos/158651/news-newsletter-newspaper-information-158651.jpeg?w=700&h=700", "author": "
This test checks the properties and therefore the following assertions are not needed.

2023-02-21 15:04 UTC, JVal-NC commented on __tests__/articles-article_id.test.js
> +describe("GET wrong pathway /non-existant", () => {
Repeat test of unhappy endpoint

2023-02-21 15:04 UTC, JVal-NC commented on __tests__/articles-article_id.test.js
> +        .get("/api/articles/37")
Good test, how about another for if the article_id is attempted with a string?

2023-02-21 15:05 UTC, JVal-NC commented on models/articles.js
> +function getArticleComments() {
Is this needed at all?

2023-02-21 15:06 UTC, JVal-NC commented on models/articles.js
> +function getArticleById(id) {
Is comment count needed in the ticket?

2023-02-21 15:09 UTC, JVal-NC commented on routes/articles.js
> +    .catch((err) => {
All catch blocks need changing to error handlers and allowing for errors other than 500, what if its an error than requires a different code or message?

2023-02-21 15:11 UTC, JVal-NC reviewed
Some comments to be included. Please include and do another PR.

2023-02-22 08:45 UTC, pippaamy commented on __tests__/articles-article_id.test.js
> +          comment_count: "2",
comment count should be a number :)

2023-02-22 08:50 UTC, pippaamy commented on __tests__/utils.test.js
>  describe("convertTimestampToDate", () => {
you need to take all these .skips off these tests

2023-02-22 08:51 UTC, pippaamy commented on index.js
>  app.use(express.json());
app.use(express.json()) not needed yet

2023-02-22 08:59 UTC, pippaamy commented on routes/articles.js
> +      res.status(200).send({ articles: sortedArticlesDesc });
Is this your controller file?

2023-02-22 09:01 UTC, pippaamy commented on __tests__/apiArticles.test.js
> +          "comment_count",
need to check that comment count is a number here

2023-02-22 09:03 UTC, pippaamy requested changes
Hiya good work! Some changes to make, you need to check that comment count comes back as a number and change some functionality to make sure it does. we shouldn't be sending up skipped tests!  Can you make a separate file for your controllers :) once you've made these changes can you send up a new pr pls 👍

2023-02-22 11:33 UTC, JVal-NC commented on controllers/articles.controller.js
> +  if (isNaN(articleId)) {
SQL will do this for us, would rely on SQL error for this.

2023-02-22 11:34 UTC, JVal-NC commented on errors/errorHandler.js
> +function errorHandler(err, req, res, next) {
Looks good but will want an error handler for 500 errors, would reccomend splitting this up. Have a look at the examples near the end of the error handling notes.

2023-02-22 11:35 UTC, JVal-NC commented on models/articles.js
> +async function getArticleById(id) {
Dont need a comment_count in this trello ticket, please remove this functionality

2023-02-22 11:37 UTC, JVal-NC commented on __tests__/articles-article_id.test.js
> +        expect(response.body.requestedArticle.comment_count).toEqual(
This is already done on line 33

2023-02-22 11:39 UTC, JVal-NC commented on __tests__/articles-article_id.test.js
> +      .get("/api/articles/'22'")
Can see what youve done but would suggest alphabetic characters rather than numbers inside quote marks would be more suitable for this test

2023-02-22 11:39 UTC, JVal-NC reviewed
Some comments to be included. Please include and do another PR.

2023-02-23 09:57 UTC, merged